### PR TITLE
adds babel support. 

### PR DESCRIPTION
**Pull request by nelsonic**
Adds ES6 Support using Babel to transpile: https://github.com/numo-labs/aws-lambda-deploy/issues/23
> relates to: https://tc-jira.atlassian.net/browse/ISEARCH-176

### CODE REVIEW

**Comment by nelsonic** [comment]
@jruts I think we can simplify this... this version is already merge-able if anyone *asks* for babel support. but I've thought of a *far* more elegant way of doing it...

**Comment by jruts** [comment]
Hey  @nelsonic  sorry for the late reply. Is there progress on the far more elegant way of doing it?

**Comment by nelsonic** [comment]
@jruts yes, I will finish this PR as soon as my current Lambda is done. will ping you when ready to review.

**Comment by nelsonic** [comment]
@jruts This is ready for review. :+1: 
Instead of *always* transpiling JS it *only* transpiles if the project has a `.babelrc` file 
So for all of *our* (`numo-labs`) lambdas it will not perform any (*unnecessary*) transpiling...
Let me know if you have any questions. :+1:

**Comment by jruts** [comment]
Looks sweet :lollipop:

**Pull request merged**
