### PR TITLE
Prevent overwriting local .env file

### PR DESCRIPTION
**Pull request by lennym**
Write the local environment variables into the dist directory's .env file rather than the local project one. This leaves the local .env file with only the user's specific variables defined.

### CODE REVIEW

**Comment by nelsonic** [comment]
@lennym good plan. waiting for build... 👍

**Comment by lennym** [comment]
I looks like you might be waiting a while... 😢

**Comment by lennym** [comment]
@nelsonic There was a problem with the zip tests not leaving a reliable fs state. It should be resolved in a1eb1a4bdc0e8e012ba1e81d22714d86b7f7629e though it may also need #45.

**Comment by lennym** [comment]
#45 is green so go for it!

**Comment by nelsonic** [comment]
Sweet! that's a *great* improvement @lennym 👍

**Pull request merged**
